name: Automation for release on slab

on:
  release:
    types: [published]

jobs:
  create-update_slab_post:
    runs-on: ubuntu-latest
    steps:
      - name: this workflow creates/updates a post on slab containing release information
        uses: Go-Go-Power-Rangers/slab-action@main
        with: 
          repo_name: ${{ github.event.repository.name }}
          repo_owner: ${{ github.repository_owner }}
          accessToken_slab: "${{ secrets.SLAB_TOKEN }}"
          accessToken_github: "bearer ${{ secrets.GITHUB_TOKEN }}"
          topic_id: "2w941vt0"